<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="#">Hue Blog</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item <?=set_active(['posts/index'])?>">
				<a class="nav-link" href="<?=WWWROOT?>/posts/index">Posts</a>
			</li>

			<?php if (isset($_SESSION['app']['user'])):?>
			<li class="nav-item <?=set_active(['posts/add'])?>">
				<a class="nav-link" href="<?=WWWROOT?>/posts/add">New Post</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="<?=WWWROOT?>/session/logout">Logout</a>
			</li>
			<?php else:?>
			<li class="nav-item">
				<a class="nav-link <?=set_active(['session/login', 'login'])?>" href="<?=WWWROOT?>/session/login">Login</a>
			</li>
			<?php endif?>
		</ul>
		<form class="form-inline my-2 my-lg-0">
			<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
			<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
		</form>
	</div>
</nav>