<!DOCTYPE html>
<html lang="en">
<head>
	<?php get_template('head', ['page_title'=>$post['title']]);?>
</head>
<body>
	<?php get_template('navbar');?>

	<div class="container">
		<h2><?=$post['title']?></h2>
		<p>
			<small>Posted by <strong><?=$post['user_name']?></strong> in <strong><?=$post['category_name']?></strong> at <strong><?=format_date($post['created_at'], 'd/m/Y')?></strong></small><br>
		</p>
		
		<p><?=$post['content']?></p>

		<p><a href="<?=WWWROOT?>" class="btn btn-secondary">Back to posts</a></p>
	</div>

	<?php get_template('scripts');?>
</body>
</html>